name: flutter_markdown_community
description: A pork from the original [Flutter_Markdown](https://pub.dev/packages/flutter_markdown). A Markdown renderer for Flutter. 
  Create rich text output, including text styles, tables, links, and more, from plain text data formatted with simple Markdown tags.
repository: https://github.com/flutter/packages/tree/main/packages/flutter_markdown_community
# issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+flutter_markdown%22
version: 0.7.7+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  markdown: ^7.3.0
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  leak_tracker_flutter_testing: any
  mockito: ^5.5.1
  standard_message_codec: ^0.0.1+4

topics:
  - markdown
  - widgets
